function SetupGame(level) {
  if (level === 1) {
    return [
      { id: 1, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 2, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 3, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 4, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 5, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 6, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 7, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 8, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 9, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 10, color: "bg-yellow-300", isFlipped: false, disabled: false },
      { id: 11, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 12, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 13, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 14, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 15, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 16, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 17, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 18, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 19, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 20, color: "bg-yellow-300", isFlipped: false, disabled: false },
    ].sort((a, b) => 0.5 - Math.random());
  } else if (level === 2) {
    return [
      { id: 1, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 2, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 3, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 4, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 5, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 6, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 7, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 8, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 9, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 10, color: "bg-yellow-300", isFlipped: false, disabled: false },
      { id: 11, color: "bg-emerald-300", isFlipped: false, disabled: false },
      { id: 12, color: "bg-teal-300", isFlipped: false, disabled: false },
      { id: 13, color: "bg-fuchsia-300", isFlipped: false, disabled: false },
      { id: 14, color: "bg-sky-300", isFlipped: false, disabled: false },
      { id: 15, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 16, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 17, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 18, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 19, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 20, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 21, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 22, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 23, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 24, color: "bg-yellow-300", isFlipped: false, disabled: false },
      { id: 25, color: "bg-emerald-300", isFlipped: false, disabled: false },
      { id: 26, color: "bg-teal-300", isFlipped: false, disabled: false },
      { id: 27, color: "bg-fuchsia-300", isFlipped: false, disabled: false },
      { id: 28, color: "bg-sky-300", isFlipped: false, disabled: false },
    ].sort((a, b) => 0.5 - Math.random());
  } else if (level === 3) {
    return [
      { id: 1, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 2, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 3, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 4, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 5, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 6, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 7, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 8, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 9, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 10, color: "bg-yellow-300", isFlipped: false, disabled: false },
      { id: 11, color: "bg-emerald-300", isFlipped: false, disabled: false },
      { id: 12, color: "bg-teal-300", isFlipped: false, disabled: false },
      { id: 13, color: "bg-fuchsia-300", isFlipped: false, disabled: false },
      { id: 14, color: "bg-sky-300", isFlipped: false, disabled: false },
      { id: 15, color: "bg-indigo-300", isFlipped: false, disabled: false },
      { id: 16, color: "bg-violet-300", isFlipped: false, disabled: false },
      { id: 17, color: "bg-red-300", isFlipped: false, disabled: false },
      { id: 18, color: "bg-pink-300", isFlipped: false, disabled: false },
      { id: 19, color: "bg-green-300", isFlipped: false, disabled: false },
      { id: 20, color: "bg-blue-300", isFlipped: false, disabled: false },
      { id: 21, color: "bg-purple-300", isFlipped: false, disabled: false },
      { id: 22, color: "bg-orange-300", isFlipped: false, disabled: false },
      { id: 23, color: "bg-lime-300", isFlipped: false, disabled: false },
      { id: 24, color: "bg-cyan-300", isFlipped: false, disabled: false },
      { id: 25, color: "bg-amber-300", isFlipped: false, disabled: false },
      { id: 26, color: "bg-yellow-300", isFlipped: false, disabled: false },
      { id: 27, color: "bg-emerald-300", isFlipped: false, disabled: false },
      { id: 28, color: "bg-teal-300", isFlipped: false, disabled: false },
      { id: 29, color: "bg-fuchsia-300", isFlipped: false, disabled: false },
      { id: 30, color: "bg-sky-300", isFlipped: false, disabled: false },
      { id: 31, color: "bg-indigo-300", isFlipped: false, disabled: false },
      { id: 32, color: "bg-violet-300", isFlipped: false, disabled: false },
    ].sort((a, b) => 0.5 - Math.random());
  }
  return console.log("Something went wrong loading cards");
}

export default SetupGame;
